zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

# Internationalization
spring.messages.basename: messages/messages

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: docker
  opentracing:
  jaeger:
    http-sender:
      url: http://otel-collector-core-jaeger.opentelemetry.svc.cluster.local:14268/api/traces
eureka:
  client:
    serviceUrl:
      defaultZone: http://petclinic-discovery-server:8761/eureka/
