server:
  port: 8761

spring:
  config:
    activate:
      on-profile: docker

eureka:
  instance:
    hostname: petclinic-discovery-server
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://petclinic-discovery-server:8761/eureka/

